# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
