# Generated by Django 3.2.13 on 2022-06-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0003_trucktrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default=None, max_length=200, verbose_name='Модель самосвала')),
                ('capacity', models.IntegerField(default=0, verbose_name='Максимальная грузоподъемность')),
            ],
        ),
        migrations.RemoveField(
            model_name='truck',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='weight',
        ),
        migrations.AlterField(
            model_name='trucktrip',
            name='truck',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='overweight.truck'),
        ),
        migrations.AddField(
            model_name='truck',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
        migrations.AddField(
            model_name='trucktrip',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
    ]
