# Generated by Django 3.2.13 on 2022-06-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0004_auto_20220617_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='model_name',
            field=models.CharField(default='', max_length=200, verbose_name='Модель самосвала'),
        ),
        migrations.AlterField(
            model_name='trucktrip',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
        migrations.AlterField(
            model_name='trucktrip',
            name='truck',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='overweight.truck'),
        ),
    ]
