# Generated by Django 3.2.13 on 2022-06-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0006_alter_truck_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
    ]
