# Generated by Django 3.2.13 on 2022-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0008_auto_20220617_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucktrip',
            name='weight',
            field=models.IntegerField(default=0, null=True, verbose_name='Текущий вес'),
        ),
    ]
