# Generated by Django 3.2.13 on 2022-06-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0009_alter_trucktrip_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='model',
        ),
        migrations.RemoveField(
            model_name='truckmodel',
            name='model_name',
        ),
    ]
