# Generated by Django 3.2.13 on 2022-06-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0010_auto_20220617_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='model',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='model_name',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Модель самосвала'),
        ),
    ]
