# Generated by Django 3.2.13 on 2022-06-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0011_auto_20220617_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='model',
        ),
        migrations.RemoveField(
            model_name='trucktrip',
            name='model',
        ),
        migrations.DeleteModel(
            name='TruckModel',
        ),
    ]
