# Generated by Django 3.2.13 on 2022-06-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0012_auto_20220617_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=200, null=True, verbose_name='Модель самосвала')),
                ('capacity', models.IntegerField(default=0, null=True, verbose_name='Максимальная грузоподъемность')),
            ],
        ),
        migrations.AlterField(
            model_name='trucktrip',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Текущий вес'),
        ),
        migrations.AddField(
            model_name='truck',
            name='model',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
        migrations.AddField(
            model_name='trucktrip',
            name='model',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
    ]
