# Generated by Django 3.2.13 on 2022-06-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overweight', '0013_auto_20220617_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucktrip',
            name='model',
            field=models.ForeignKey(db_column='Модель', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='overweight.truckmodel'),
        ),
    ]
